modLoader="javafml"
loaderVersion="[47,)"
license="MIT"
issueTrackerURL="https://github.com/EwyBoy/Cultivated-Tech/issues"

[[mods]]
modId="cultivatedtech"
displayName="Cultivated Tech"
version="1.0.0"
authors="Ewy"
credits="Test"
description="Test"

[[dependencies.cultivatedtech]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="AFTER"
side="BOTH"

[[dependencies.cultivatedtech]]
modId="minecraft"
mandatory=true
versionRange="[1.20.1,1.21]"
ordering="NONE"
side="BOTH"